import { useEffect, useRef } from "react";
import PageHeader from "../components/layout/PageHeader";
import ChatMessage from "../components/chat/ChatMessage";
import ChatInput from "../components/chat/ChatInput";
import Loader from "../components/common/Loader";
import Button from "../components/common/Button";
import { useRepository } from "../context/RepositoryContext";
import useChat from "../hooks/useChat";
export default function ChatPage() {
  const { activeRepository, goToImport } = useRepository(); const { messages,busy,error,setError,send }=useChat(); const bottom=useRef(null);
  useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages,busy]);
  return <><PageHeader eyebrow="ASK QUESTIONS, GET CONTEXT" title="Code chat" description="Ask questions grounded in your active repository."/><section className="card chat-layout"><div className="chat-main"><div className="chat-header"><div className="chat-bot-avatar">✳</div><div><strong>CodeLens assistant</strong><p>{activeRepository ? `Grounded in ${activeRepository.repository}` : "No active repository"}</p></div><span className="chat-context-badge">RAG powered</span></div><div className="chat-messages">{!messages.length ? <div className="chat-empty"><div className="chat-empty-symbol">✳</div><h2>What would you like to understand?</h2><p className="muted">Ask about architecture, functions, authentication, or data flow.</p>{!activeRepository&&<Button onClick={goToImport}>Import repository →</Button>}<div className="suggestion-list">{["Explain the overall architecture","Where is authentication handled?","How does the frontend communicate with the backend?"].map(q=><button className="suggestion" key={q} disabled={!activeRepository||busy} onClick={()=>send(q)}>✧ {q}<span className="suggestion-arrow">↗</span></button>)}</div></div>:messages.map((message,i)=><ChatMessage key={i} message={message}/>)}{busy&&<Loader label="CodeLens is thinking…"/>}<div ref={bottom}/></div>{error&&<div className="alert alert-error">{error}<button onClick={()=>setError("")}>×</button></div>}<ChatInput disabled={!activeRepository||busy} onSend={send}/></div><aside className="chat-aside"><p className="eyebrow">CHAT CONTEXT</p><h3>Repository details</h3>{activeRepository ? <><div className="context-repo-icon">⌘</div><strong>{activeRepository.repository}</strong><p className="muted context-path">{activeRepository.repository_path}</p><div className="context-divider"/><div className="context-info"><span>Status</span><strong className="text-success">● Active</strong></div></>:<p className="muted">Import and activate a repository to provide code context.</p>}<div className="context-tip"><strong>Tip for better answers</strong><p>Ask specific questions about files, functions, and data flow.</p></div></aside></section></>;
}
