import { useNavigate } from "react-router-dom";
import RepositoryImportForm from "../components/repository/RepositoryImportForm";
import ImportProgress from "../components/repository/ImportProgress";
import RepositoryCard from "../components/repository/RepositoryCard";
import { useRepository } from "../context/RepositoryContext";
import useImportRepository from "../hooks/useImportRepository";
import ErrorMessage from "../components/common/ErrorMessage";
export default function ImportPage() {
  const { health, repositories, loading, refresh, activate, setActiveRepository } = useRepository(); const navigate = useNavigate();
  const { start, busy, message, error, setError } = useImportRepository({ onSuccess: async result => { await refresh(); if (result.repository_path) setActiveRepository({ repository: result.repository || "Imported repository", repository_path: result.repository_path }); navigate("/dashboard"); } });
  async function activateRepo(path) { try { await activate(path); navigate("/dashboard"); } catch (e) { setError(e.message); } }
  return <div className="import-screen"><header className="import-topbar"><div className="brand"><span className="brand-mark">⌘</span><span><strong>CodeLens</strong><small>AI code companion</small></span></div><span className={`api-status ${health}`}><i className="status-dot"/>API {health}</span></header>
    <div className="import-hero-grid"><section className="import-hero-copy"><span className="hero-chip dark-chip">✦ CODEBASE INTELLIGENCE</span><h1>Your codebase,<br/><span>finally in focus.</span></h1><p>Connect a GitHub repository and turn an unfamiliar codebase into something you can explore, understand, and ask questions about.</p><div className="feature-points"><span>✓ AI-powered code chat</span><span>✓ Architecture insights</span><span>✓ Searchable code chunks</span></div><div className="import-illustration"><div className="illus-code"><div className="window-dots"><i/><i/><i/></div><div className="illus-line">import <b>Codebase</b> from './repo';</div><div className="illus-line">const context = <b>await</b> index(code);</div><div className="illus-line muted-line">// discover how it all connects</div><div className="illus-line">return <b>insights</b>(context);</div></div><div className="illus-float float-one">✧ <small>Semantic search</small></div><div className="illus-float float-two">⌘ <small>Code context</small></div></div></section>
      <section className="import-form-column"><div className="import-card-large"><div className="import-card-icon">↗</div><p className="eyebrow">LET'S GET STARTED</p><h2>Import your repository</h2><p className="muted">Paste a GitHub URL. CodeLens will clone your repository and build an index so you can explore it with AI.</p><ErrorMessage message={error} onDismiss={() => setError("")}/><RepositoryImportForm onSubmit={url => start(url).catch(()=>{})} busy={busy}/><ImportProgress message={message} busy={busy}/><div className="secure-note">Repository processing runs through your configured CodeLens backend.</div><div className="import-divider"><span>OR</span></div><strong className="saved-title">Previously imported repositories</strong><div className="saved-repo-list">{loading ? <p className="muted">Loading repositories…</p> : repositories.length ? repositories.map(repo => <RepositoryCard key={repo.normalized_url || repo.repo_url || repo.repository_path} repo={repo} active={false} onActivate={activateRepo}/>) : <p className="muted">No saved repositories yet. Import your first repository above.</p>}</div></div><div className="import-help"><strong>What happens after import?</strong><p>Your files are chunked and indexed. Then explore architecture, inspect index metadata, and ask questions in Code chat.</p></div></section></div><footer className="import-footer"><span>CodeLens · Built for curious developers</span><span>Backend {health}</span></footer></div>;
}
